config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions
  resources :users
  resources :clients do
    member do
      get :credits, :deposits, :bills,
      :credit_transactions, :deposit_transactions, :bill_transactions, :transactions,
      :archive_deposits, :archive_credits, :archive_bills,
      :new_bill, :new_credit, :new_deposit
    end
  end
  resources :client_deposits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_credits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_bills do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :deposits
  resources :credits
  resources :bills
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/search' => 'sessions#search'
  get '/contacts' => 'sessions#contacts'


  end

app/models/user.rb
class User < ApplicationRecord
  before_create :create_remember_token
  has_secure_password
  validates :login, uniqueness: true
  VALID_PASSWORD_REGEX = /\A[\w]+\z/
  validates :password, :confirmation => true, presence: true, length: { in: 6..20 },
  format: { with: VALID_PASSWORD_REGEX }
  validates :password_confirmation, :presence => true

    def User.new_remember_token
      SecureRandom.urlsafe_base64
    end
    def User.encrypt(token)
      Digest::SHA1.hexdigest(token.to_s)
    end
    private
      def create_remember_token
        self.remember_token = User.encrypt(User.new_remember_token)
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user
  before_action :signed_as_admin, except: [:show]
  before_action :correct_manager

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
    @user.status = 1;
    if @user.save
      flash[:success] = "Successfully added!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      flash[:success] = "Successfully updated!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "Successfully deleted!"
    redirect_to '/users'
  end

  def user_params
    params.require(:user).permit(:login, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@user.errors.count, "error") %> prohibited
       this client from being saved:
     </h2>
     <ul>
       <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

<div>
   <div>
       <div class="label">Login:</div>
       <div class="field">
           <%= f.text_field :login, placeholder: "Login" %>
       </div>
   </div>

   <div>
       <div class="label">Password:</div>
       <div class="field">
           <%= f.password_field :password, placeholder: "Password"  %>
       </div>
   </div>

   <div>
       <div class="label">Password confirmation:</div>
       <div class="field">
           <%= f.password_field :password_confirmation, placeholder: "Password confirmation"  %>
       </div>
   </div>

 <p>
   <%= f.submit %>
 </p>
<% end %>

app/views/users/edit.html.erb
<title>Edit User</title>
<div class="middle">
<h1 class="h1-basic">Edit user</h1>
<%= render 'form' %>
<button class="button orange" style="float: left" onclick="location.href='/users/<%="#{params[:id]}"%>'">Back</button>

app/views/users/index.html.erb
<title>Users</title>
<div class="middle">
<h1  class="h1-basic">Users</h1>
<table>
  <tr>
    <th>Login</th>
    <th>Status</th>
    <th>Date</th>
  </tr>

  <% @user.each do |user| %>
    <tr>
      <td><%= user.login %></td>
      <% if user.status == 2 %>
        <td>Admin</td>
      <% elsif user.status == 1 %>
        <td>Manager</td>
      <% else %>
        <td>Client</td>
      <% end %>
      <td><%= user.created_at %></td>
      <% if user.status != 0 %>
        <td>
          <button class="button orange" onclick="location.href='<%=edit_user_path(user)%>'">Edit</button>
          <button class="button blue" onclick="location.href='<%=user_path(user)%>'">Show</button>
          <%= link_to "Delete", user_path(user), class:"button red", method: :delete, data: { confirm: 'Are you sure?' }, style: 'font-size: 11px !important;' %>
        </td>
      <% else %>
        <td>
          <button class="button orange" onclick="location.href='<%=edit_client_path(Client.find(user.client_id))%>'">Edit</button>
          <button class="button blue" onclick="location.href='<%=client_path(Client.find(user.client_id))%>'">Show</button>
        </td>
        <% end %>
      <td width='10'></td>
    </tr>
  <% end %>
</table>
<button class="button green" style="float: left" onclick="location.href='<%= new_user_path %>'">New manager</button>
</div>

app/views/users/new.html.erb
<title>Add Manager</title>
<div class="middle">
<h1  class="h1-basic">New manager</h1>
<%= render 'form' %>
<button class="button orange" style="float: left" onclick="location.href='/users'">Back</button>

app/views/users/show.html.erb
<title>User</title>
<div class="middle">
<h1  class="h1-basic">User</h1>
<p>
  <strong>Login:</strong>
  <%= @user.login %>
</p>