config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions
  resources :users
  resources :clients do
    member do
      get :credits, :deposits, :bills,
      :credit_transactions, :deposit_transactions, :bill_transactions, :transactions,
      :archive_deposits, :archive_credits, :archive_bills,
      :new_bill, :new_credit, :new_deposit
    end
  end
  resources :client_deposits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_credits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_bills do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :deposits
  resources :credits
  resources :bills
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/search' => 'sessions#search'
  get '/contacts' => 'sessions#contacts'


  end

app/models/client.rb
class Client < ApplicationRecord
  has_many :client_bills, dependent: :destroy
  has_many :client_credits, dependent: :destroy
  has_many :client_deposits, dependent: :destroy
  before_save {
    email.downcase!
    passport.upcase!
  }
  validates :full_name,  presence: true, length: { maximum: 50 }

  VALID_PHONE_REGEX = /\A\+([\d]){12}+\z/ # "+380123456789"
  validates :phone, presence: true, length: { maximum: 20 }, uniqueness: true,
  format: { with: VALID_PHONE_REGEX }

  VALID_PASSPORT_REGEX = /\A([A-Za-z]){2}([\d]){6}+\z/ # "AA202020"
  validates :passport, presence: true, length: { is: 8 },
  format: { with: VALID_PASSPORT_REGEX }
  VALID_ID_NUMBER_REGEX = /\A([\d]){10}\z/
  validates :id_number, presence: true, length: { is: 10 },
  format: { with: VALID_ID_NUMBER_REGEX }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i  # Email validates "abc@ukr.net"
  validates :email, presence: true, length: { maximum: 20 },
  format: { with: VALID_EMAIL_REGEX }

  validates  :address, presence: true, length: { maximum: 50 }

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :signed_in_user
  before_action :signed_as_manager, except: [:show, :deposits, :credits, :bills,
     :credit_transactions, :deposit_transactions, :bill_transactions, :transactions,
   :archive_deposits, :archive_credits, :archive_bills]
  before_action :correct_user

  def index
    if params[:q] == nil
      @client = Client.all
    elsif (Integer (params[:q]) rescue nil) != nil
      @client = Client.where('id_number = ?', params[:q])
    elsif (Integer (params[:q][2]) rescue nil) != nil
      @client = Client.where('passport = ?', params[:q])
    else
      @client = Client.where('full_name = ?', params[:q])
    end
  end

  def show
    @client = Client.find(params[:id])
  end

  def deposits
    @client_deposit = ClientDeposit.where('client_id=? AND status=?', params[:id], true)
  end

  def credits
    @client_credit = ClientCredit.where('client_id=? AND status=?', params[:id], true)
  end

  def bills
    @client_bill = ClientBill.where('client_id=? AND status=?', params[:id], true)
  end

  def archive_deposits
    @archive_client_deposit = ClientDeposit.where('client_id=? AND status=?', params[:id], false)
  end

  def archive_credits
    @archive_client_credit = ClientCredit.where('client_id=? AND status=?', params[:id], false)
  end

  def archive_bills
    @archive_client_bill = ClientBill.where('client_id=? AND status=?', params[:id], false)
  end

  def credit_transactions
  	@credit_transaction = CreditOperation.where('client_credit_id = ? ', params[:id])
  end

  def deposit_transactions
  	@deposit_transaction = DepositOperation.where('client_deposit_id = ?', params[:id])
  end

  def bill_transactions
  	@bill_transaction = BillOperation.where('client_bill_id = ?', params[:id])
  end

  def transactions
  	credit_t = CreditOperation.where('client_credit_id = ? ', params[:id])
  	deposit_t = DepositOperation.where('client_deposit_id = ?', params[:id])
  	bill_t = BillOperation.where('client_bill_id = ?', params[:id])
  	@transaction = credit_t + deposit_t + bill_t
  	@transaction ||= []
  	@transaction.sort! { |x, y| y[:created_at] <=> x[:created_at]}
  end

  def new_deposit
    @client_deposit = ClientDeposit.new
  end

  def new_credit
    @client_credit = ClientCredit.new
  end

  def new_bill
    @client_bill = ClientBill.new
  end

  def new
    @client = Client.new
    @user = User.new
  end

  def edit
    @client = Client.find(params[:id])
    @user = User.find_by_client_id(params[:id])
  end

  def create
    @client = Client.new(client_params)
    @user = User.new(params.require(:user).permit(:password, :password_confirmation))
    @user.login = @client.phone
    @user.status = 0
    if !@client.valid? || !@user.valid?
      @user.valid?
      render 'new'
    else
      @client.save
      @user.client_id = @client.id
      @user.save
      flash[:success] = "Successfully added!"
      redirect_to @client
    end
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      flash[:success] = "Successfully updated!"
      redirect_to @client
    else
      render 'edit'
    end
  end

  def destroy
    @client = Client.find(params[:id])
    @user = User.find_by_client_id(@client.id)
    if @client && @user
      @client.destroy
      @user.destroy
      flash[:success] = "Successfully deleted!"
    end
    redirect_to ''
  end

  private

    # def client_deposit_params
    #   params.require(:client_deposit).permit(:deposit_id, :sum)
    # end
    #
    # def client_credit_params
    #   params.require(:client_credit).permit(:credit_id, :sum)
    # end
    #
    # def client_bill_params
    #   params.require(:client_bill).permit(:currency_id, :sum)
    # end

    def client_params
      params.require(:client).permit(:full_name, :phone, :passport, :id_number, :email, :address, :birth, :sex)
    end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>

   <% if @client.errors.any? || @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@client.errors.count + @user.errors.count, "error") %> prohibited
        this client from being saved:
      </h2>

        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

      <ul>
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>

    </div>
  <% end %>

<div>

    <div>
        <div class="label">Full Name:</div>
        <div class="field">
            <%= f.text_field :full_name, placeholder: "Full Name"  %>
        </div>
    </div>

    <div>
        <div class="label">Sex:</div>
        <div class="field">
            <%= f.select(:sex) do %>
              <% [['Male', true], ['Female', false]].each do |c| -%>
                <%= content_tag(:option, c.first, value: c.last) %>
              <% end %>
            <% end %>
        </div>
    </div>

    <div>
        <div class="label">Birth</div>
        <div class="field">
            <%= f.date_field :birth, placeholder: "Birthday"  %>
        </div>
    </div>

    <div>
        <div class="label">Address</div>
        <div class="field">
            <%= f.text_field :address, placeholder: "Address"  %>
        </div>
    </div>

    <div>
        <div class="label">Phone:</div>
        <div class="field">
            <%= f.text_field :phone, placeholder: "Phone"  %>
        </div>
    </div>

    <div>
        <div class="label">Passport:</div>
        <div class="field">
            <%= f.text_field :passport, placeholder: "Passport"  %>
        </div>
    </div>

    <div>
        <div class="label">ID Number:</div>
        <div class="field">
            <%= f.text_field :id_number, placeholder: "Identification Number"  %>
        </div>
    </div>

    <div>
        <div class="label">Email</div>
        <div class="field">
            <%= f.text_field :email, placeholder: "Email"  %>
        </div>
    </div>

    <div>
        <div class="label">Password:</div>
        <div class="field">
            <%= password_field(:user, :password, placeholder: "Password") %>
        </div>
    </div>

    <div>
        <div class="label">Password Confirmation:</div>
        <div class="field">
            <%= password_field(:user, :password_confirmation, placeholder: "Password Confirmation") %>
        </div>
    </div>



  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/clients/archive_deposits.html.erb
<title>Archive Deposits</title>
<div class="white-wrap">
<%= render "layouts/client_menu" %>
<div class="center">
<h1 class="h1-basic">Client's deposits archive</h1>
<table>
  <tr>
    <th>Deposit ID</th>
    <th>Deposit Type</th>
    <th>Sum</th>
    <th>Date archived</th>
  </tr>


  <% @archive_client_deposit.each do |archive_client_deposit| %>
    <tr>
      <td><%= archive_client_deposit.id %></td>
      <td><%= Deposit.find(archive_client_deposit.deposit_id).name %></td>
      <td><%= archive_client_deposit.sum %></td>
      <td><%= archive_client_deposit.updated_at %></td>
      <td><button class="button blue" onclick="location.href='<%=client_deposit_path(archive_client_deposit)%>'">Show</button></td>
      <td width='10'></td>
    </tr>
      <% end %>
</table>
</div>

app/views/clients/bill_transactions.html.erb
<title>Bill Transactions</title>
<div class="white-wrap">
<%= render "layouts/client_menu" %>
<div class="center">
<h1 class="h1-basic">Bill Transactions</h1>
  <table>
  <tr>
    <th>ID</th>
    <th>Sum</th>
    <th>Date</th>
  </tr>
    <% @bill_transaction.each do |bill_transaction| %>
    <tr>
      <td><%= bill_transaction.client_deposit_id %></td>
      <td><%= bill_transaction.sum %></td>
      <td><%= bill_transaction.created_at %></td>
  </tr>
  <% end %>

</table>
</div>

app/views/clients/bills.html.erb
<title>Client Bills</title>
<div class="white-wrap">
<%= render "layouts/client_menu" %>
<div class="center">
<h1 class="h1-basic">Client's bills</h1>
<table>
  <tr>
    <th>Bill ID</th>
    <th>Currency</th>
    <th>Sum</th>
    <th>Date opened</th>
  </tr>



  <% @client_bill.each do |client_bill| %>
    <tr>
      <td><%= client_bill.id %></td>
      <td><%= Currency.find(client_bill.currency_id).name %></td>
      <td><%= client_bill.sum %></td>
      <td><%= client_bill.created_at %></td>
      <td><% if is_manager? %> <button class="button red" onclick="location.href='/client_bills/<%="#{client_bill.id}"%>/to_archive'">In archive</button>
      <button class="button orange" onclick="location.href='<%=edit_client_bill_path(client_bill)%>'">Edit</button>
          <% end %>
      <button class="button blue" onclick="location.href='<%=client_bill_path(client_bill)%>'">Show</button></td>
      <td width='10'></td>
    </tr>
      <% end %>
</table>
</div>

app/views/clients/credit_transactions.html.erb
<title>Credit Transactions</title>
<div class="white-wrap">
<%= render "layouts/client_menu" %>
<div class="center">
<h1 class="h1-basic">Credit Transactions</h1>
  <table>
  <tr>
    <th>ID</th>
    <th>Sum</th>
    <th>Date</th>
  </tr>
    <% @credit_transaction.each do |credit_transaction| %>
    <tr>
      <td><%= credit_transaction.client_deposit_id %></td>
      <td><%= credit_transaction.sum %></td>
      <td><%= credit_transaction.created_at %></td>
  </tr>
  <% end %>

</table>
</div>
</div>

app/views/clients/credits.html.erb
<title>Client Credits</title>
<div class="white-wrap">
<%= render "layouts/client_menu" %>
<div class="center">
<h1 class="h1-basic">Client's credits</h1>
<table>
  <tr>
    <th>Credit ID</th>
    <th>Credit Type</th>
    <th>Sum</th>
    <th>Date opened</th>
  </tr>



  <% @client_credit.each do |client_credit| %>
    <tr>
      <td><%= client_credit.id %></td>
      <td><%= Credit.find(client_credit.credit_id).name %></td>
      <td><%= client_credit.sum %></td>
      <td><%= client_credit.created_at %></td>
      <td><% if is_manager? %> <button class="button red" onclick="location.href='/client_credits/<%="#{client_credit.id}"%>/to_archive'">In archive</button>
      <button class="button orange" onclick="location.href='<%=edit_client_credit_path(client_credit)%>'">Edit</button>
          <% end %>
      <button class="button blue" onclick="location.href='<%=client_credit_path(client_credit)%>'">Show</button></td>
      <td width='10'></td>
    </tr>
      <% end %>
</table>
</div>

app/views/clients/deposits.html.erb
<title>Client Deposits</title>
<div class="white-wrap">
<%= render "layouts/client_menu" %>
<div class="center">
<h1 class="h1-basic">Client's deposits</h1>
<table>
  <tr>
    <th>Deposit ID</th>
    <th>Deposit Type</th>
    <th>Sum</th>
    <th>Date opened</th>
  </tr>


  <% @client_deposit.each do |client_deposit| %>
    <tr>
      <td><%= client_deposit.id %></td>
      <td><%= Deposit.find(client_deposit.deposit_id).name %></td>
      <td><%= client_deposit.sum %></td>
      <td><%= client_deposit.created_at %></td>
      <td><% if is_manager? %> <button class="button red" onclick="location.href='/client_deposits/<%="#{client_deposit.id}"%>/to_archive'">In archive</button>
      <button class="button orange" onclick="location.href='<%=edit_client_deposit_path(client_deposit)%>'">Edit</button>
          <% end %>
      <button class="button blue" onclick="location.href='<%=client_deposit_path(client_deposit)%>'">Show</button></td>
      <td width='10'></td>
    </tr>
      <% end %>
</table>
</div>

app/views/clients/index.html.erb
<title>Clients</title>
<div class="white-wrap">
<div class="middle">
<div>
  <%= form_tag("/clients", method: :get) do %>
<input type="text" placeholder="Search..." name="q"><br/>
<button class="button blue" style="float: left;">Find</button>
<% end %>
</div>
<h1 style="margin-top: 50px;" class="h1-basic">Clients</h1>
<table>
  <tr>
    <th>Full Name</th>
    <th>Phone</th>
    <th>Passport</th>
    <th>ID Number</th>
    <th>E-mail</th>
    <th>Address</th>
  </tr>

  <% @client.each do |client| %>
    <tr>
      <td><%= client.full_name %></td>
      <td><%= client.phone %></td>
      <td><%= client.passport %></td>
      <td><%= client.id_number %></td>
      <td><%= client.email %></td>
      <td><%= client.address %></td>
      <td><button class="button orange" onclick="location.href='<%=edit_client_path(client)%>'">Edit</button>
      <button class="button blue" onclick="location.href='<%=client_path(client)%>'">Show</button></td>
      <td width='10'></td>
    </tr>
  <% end %>
</table>
<button class="button green" style="float: left" onclick="location.href='<%=new_client_path%>'">New client</button>
</div>

app/views/clients/new.html.erb
<title>Add Client</title>
<div class="middle">
<h1 class="h1-basic">New client</h1>
<%= render 'form' %>
<button class="button orange" style="float: left" onclick="location.href='/search'">Back</button>

app/views/clients/new_bill.html.erb
<title>Add Client Bill</title>
<div class="middle">
<h1 class="h1-basic">New client bill</h1>
<%= render "client_bills/form" %>
<button class="button orange" style="float: left" onclick="location.href='/clients/<%="#{params[:id]}"%>'">Back</button>

app/views/clients/new_credit.html.erb
<title>Add Client Credit</title>
<div class="middle">
<h1 class="h1-basic">New client credit</h1>
<%= render "client_credits/form" %>
<button class="button orange" style="float: left" onclick="location.href='/clients/<%="#{params[:id]}"%>'">Back</button>

app/views/clients/new_deposit.html.erb
<title>Add Client Deposit</title>
<div class="middle">
<h1 class="h1-basic">New client deposit</h1>
<%= render "client_deposits/form" %>
<button class="button orange" style="float: left" onclick="location.href='/clients/<%="#{params[:id]}"%>'">Back</button>

app/views/clients/show.html.erb
<title>Profile</title>
<%= render "layouts/client_menu" %>
<div class="middle">
<p>
  <strong>Full Name:</strong>
  <%= @client.full_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @client.phone %>
</p>
<p>

<p>
  <strong>Passport:</strong>
  <%= @client.passport %>
</p>

<p>
  <strong>ID Number:</strong>
  <%= @client.id_number %>
</p><p>
  <strong>E-mail:</strong>
  <%= @client.email %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>
</div>

app/views/clients/transactions.html.erb
<title>Transactions</title>
<div class="white-wrap">
<%= render "layouts/client_menu" %>
<div class="center">
<h1 class="h1-basic">Transactions</h1>
  <table>
  </tr>
  <tbody>
  <tr>
    <th>Тип Услуги</th>
    <th>ID</th>
    <th>Sum</th>
    <th>Date</th>
  </tr>
    <% @transaction.each do |transaction| %>
    <tr>
      <% if transaction[:client_deposit_id] != nil %>
      <td>Депозит</td>
      <td><%= transaction[:client_deposit_id] %></td>
      <% elsif transaction[:client_credit_id] != nil %>
      <td>Кредит</td>
      <td><%= transaction[:client_credit_id] %></td>
      <% else %>
      <td>Счет</td>
      <td><%= transaction[:client_bill_id] %></td>
      <% end %>
      <td><%= transaction.sum %></td>
      <td><%= transaction.created_at %></td>
    <% end %>
</table>