config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions
  resources :users
  resources :clients do
    member do
      get :credits, :deposits, :bills,
      :credit_transactions, :deposit_transactions, :bill_transactions, :transactions,
      :archive_deposits, :archive_credits, :archive_bills,
      :new_bill, :new_credit, :new_deposit
    end
  end
  resources :client_deposits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_credits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_bills do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :deposits
  resources :credits
  resources :bills
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/search' => 'sessions#search'
  get '/contacts' => 'sessions#contacts'


  end

app/models/credit.rb
class Credit < ApplicationRecord
  belongs_to :currency

  validates :name,  presence: true, uniqueness: true, length: { maximum: 50 }

  VALID_MAX_SUM_REGEX = /\A([1-9]{1}[0-9]*|0).[0-9]{1,2}\z/
  validates :max_sum, presence: true,
  format: { with: VALID_SUM_REGEX }

  validates :term, numericality: { only_integer: true }

  VALID_RATE_REGEX = /\A(([1-9]{1}|[1-9]{1}[0-9]{1}|0).[0-9]{1,2}|100,00)\z/ # 0,12 9,12, 16,00, 100,00 (%)
  validates :rate, presence: true,
  format: { with: VALID_RATE_REGEX }

  
  validate :check_currency
  private
  def check_currency
    errors.add(:currency_id, "can't find currency") unless Currency.exists?(self.currency_id)
  end

end

app/controllers/credits_controller.rb
class CreditsController < ApplicationController
  before_action :signed_as_manager, except: [:index, :show]

  def index
    @credit = Credit.all
  end

  def show
    @credit = Credit.find(params[:id])
  end

  def new
    @credit = Credit.new
  end

  def create
    @credit = Credit.new(credit_params)
    if @credit.save
      flash[:success] = "Successfully added!"
      redirect_to '/credits'
    else
      render 'new'
    end
  end

  def edit
    @credit = Credit.find(params[:id])
  end
  def update
    @credit = Credit.find(params[:id])
    if @credit.update(credit_params)
      flash[:success] = "Successfully updated!"
      redirect_to '/credits'
    else
      render 'edit'
    end
  end

  def destroy
    @credit = Credit.find(params[:id])
    @credit.destroy
    flash[:success] = "Successfully deleted!"
    redirect_to '/credits'
  end

  private
    def credit_params
      params.require(:credit).permit(:name, :currency_id, :term, :rate, :max_sum, :penalty)
    end

end

app/helpers/credits_helper.rb
module CreditsHelper
end

app/views/credits/_form.html.erb
<%= form_for @credit do |f| %>
  <% if @credit.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@credit.errors.count, "error") %> prohibited
       this client from being saved:
     </h2>
     <ul>
       <% @credit.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

<div>

   <div>
       <div class="label">Name:</div>
       <div class="field">
           <%= f.text_field :name, placeholder: "Name" %>
       </div>
   </div>

   <% currency = Currency.all %>
   <div>
       <div class="label">Currency:</div>
       <div class="field">
           <%= f.select(:currency_id) do %>
             <% currency.each do |c| -%>
               <%= content_tag(:option, c[:name] + " " + c[:symbol], value: c[:id]) %>
             <% end %>
           <% end %>
       </div>
   </div>

   <div>
       <div class="label">Term:</div>
       <div class="field">
           <%= f.text_field :term, placeholder: "Term" %>
       </div>
   </div>

   <div>
       <div class="label">Rate:</div>
       <div class="field">
           <%= f.text_field :rate, placeholder: "Rate" %>
       </div>
   </div>

   <div>
       <div class="label">Max sum:</div>
       <div class="field">
           <%= f.text_field :max_sum, placeholder: "Max sum" %>
       </div>
   </div>

   <div>
       <div class="label">Penalty:</div>
       <div class="field">
           <%= f.text_field :penalty, placeholder: "Penalty" %>
       </div>
   </div>


 <p>
   <%= f.submit %>
 </p>
<% end %>

app/views/credits/edit.html.erb
<title>Edit Credit</title>
<div class="middle">
<h1 class="h1-basic">Edit credit</h1>
<%= render 'form' %>
<button class="button orange" style="float: left" onclick="location.href='/credits'">Back</button>

app/views/credits/index.html.erb
<title>Credits</title>
<div class="white-wrap">
  <div class="middle-offers">
  <h1 class="h1-basic">Credits</h1>
  <table>
    <tr>
      <th>Credit ID</th>
      <th>Credit name</th>
      <th>Currency</th>
      <th>Term</th>
      <th>Rate</th>
      <th>Max sum</th>
      <th>Penalty</th>
    </tr>
  <% @credit.each do |credit| %>
    <tr>
      <td><%= credit.id %></td>
      <td><%= credit.name %></td>
      <td><%= Currency.find(credit.currency_id).name %></td>
      <td><%= credit.term %></td>
      <td><%= credit.rate %></td>
      <td><%= credit.max_sum %></td>
      <td><%= credit.penalty %></td>
      <% if is_manager? %>
        <td>
          <%= link_to "Delete", credit_path(credit), class:"button red", method: :delete, data: { confirm: 'Are you sure?' }, style: 'font-size: 13px !important;' %>
          <%= link_to "Edit", edit_credit_path(credit), class:"button orange", style: 'font-size: 13px !important;' %>
        </td>
      <% end %>
    </tr>
    <% end %>
</table>
<% if is_manager? %>
  <button class="button green" style="float: left" onclick="location.href='<%=new_credit_path%>'">New credit</button>
<% end %>
</div>
</div>

app/views/credits/new.html.erb
<title>Add Credit</title>
<div class="middle">
<h1 class="h1-basic">New credit</h1>
<%= render 'form' %>
<button class="button orange" style="float: left" onclick="location.href='/credits'">Back</button>