config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  resources :sessions
  resources :users
  resources :clients do
    member do
      get :credits, :deposits, :bills,
      :credit_transactions, :deposit_transactions, :bill_transactions, :transactions,
      :archive_deposits, :archive_credits, :archive_bills,
      :new_bill, :new_credit, :new_deposit
    end
  end
  resources :client_deposits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_credits do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :client_bills do
    member do
      get :to_archive
      get :new_transaction
    end
  end
  resources :deposits
  resources :credits
  resources :bills
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  get '/search' => 'sessions#search'
  get '/contacts' => 'sessions#contacts'


  end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :currency
  
  validates :name,  presence: true, uniqueness: true, length: { maximum: 50 }

  validates :term, numericality: { only_integer: true }
  
  VALID_RATE_REGEX = /\A(([1-9]{1}|[1-9]{1}[0-9]{1}|0).[0-9]{1,2}|100,00)\z/ # 0,12 9,12, 16,00, 100,00 (%)
  validates :rate, presence: true,
  format: { with: VALID_RATE_REGEX }
  #
  validates :widthdrawal, inclusion: { in: [true, false] }
  #
  validates :refill, inclusion: { in: [true, false] }

  validate :check_currency
  private
  def check_currency
    errors.add(:currency_id, "can't find currency") unless Currency.exists?(self.currency_id)
  end
  
end

app/controllers/deposits_controller.rb
class DepositsController < ApplicationController
  before_action :signed_as_manager, except: [:index, :show]

  def index
    @deposit = Deposit.all
  end

  def show
    @deposit = Deposit.find(params[:id])
  end

  def new
    @deposit = Deposit.new
  end

  def create
    @deposit = Deposit.new(deposit_params)
    if @deposit.save
      flash[:success] = "Successfully added!"
      redirect_to '/deposits'
    else
      render 'new'
    end
  end

  def edit
    @deposit = Deposit.find(params[:id])
  end
  def update
    @deposit = Deposit.find(params[:id])
    if @deposit.update(deposit_params)
      flash[:success] = "Successfully updated!"
      redirect_to '/deposits'
    else
      render 'edit'
    end
  end

  def destroy
    @deposit = Deposit.find(params[:id])
    @deposit.destroy
    flash[:success] = "Successfully deleted!"
    redirect_to '/deposits'
  end

  private
    def deposit_params
      params.require(:deposit).permit(:name, :currency_id, :term, :rate, :widthdrawal, :refill)
    end

end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/_form.html.erb
<%= form_for @deposit do |f| %>
  <% if @deposit.errors.any? %>
   <div id="error_explanation">
     <h2>
       <%= pluralize(@deposit.errors.count, "error") %> prohibited
       this client from being saved:
     </h2>
     <ul>
       <% @deposit.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
       <% end %>
     </ul>
   </div>
 <% end %>

<div>
   <div></div>

   <div>
       <div class="label">Name:</div>
       <div class="field">
           <%= f.text_field :name, placeholder: "Name" %>
       </div>
   </div>

   <% currency = Currency.all %>
   <div>
       <div class="label">Currency:</div>
       <div class="field">
     <%= f.select(:currency_id) do %>
       <% currency.each do |c| -%>
         <%= content_tag(:option, c[:name] + " " + c[:symbol], value: c[:id]) %>
       <% end %>
     <% end %>
       </div>
   </div>

   <div>
       <div class="label">Term:</div>
       <div class="field">
           <%= f.text_field :term, placeholder: "Term" %>
       </div>
   </div>

   <div>
       <div class="label">Rate:</div>
       <div class="field">
           <%= f.text_field :rate, placeholder: "Rate" %>
       </div>
   </div>

   <div>
       <div class="label">Widthdrawal:</div>
       <div class="field">
     <%= f.select(:widthdrawal) do %>
       <% [['Yes', true], ['No', false]].each do |c| -%>
         <%= content_tag(:option, c.first, value: c.last) %>
       <% end %>
     <% end %>
       </div>
   </div>

   <div>
       <div class="label">Refill:</div>
       <div class="field">
     <%= f.select(:refill) do %>
       <% [['Yes', true], ['No', false]].each do |c| -%>
         <%= content_tag(:option, c.first, value: c.last) %>
       <% end %>
     <% end %>
       </div>
   </div>

 <p>
   <%= f.submit %>
 </p>
<% end %>

app/views/deposits/edit.html.erb
<title>Edit Deposit</title>
<div class="middle">
<h1 class="h1-basic">Edit deposit</h1>
<%= render 'form' %>
<button class="button orange" style="float: left" onclick="location.href='/deposits'">Back</button>

app/views/deposits/index.html.erb
<title>Deposits</title>
<div class="white-wrap">
  <div class="middle-offers">
  <h1 class="h1-basic">Deposits</h1>
  <table>
    <tr>
      <th>Deposit ID</th>
      <th>Deposit name</th>
      <th>Currency</th>
      <th>Term</th>
      <th>Rate</th>
      <th>Widthdrawal</th>
      <th>Refill</th>
    </tr>
  <% @deposit.each do |deposit| %>
    <tr>
      <td><%= deposit.id %></td>
      <td><%= deposit.name %></td>
      <td><%= Currency.find(deposit.currency_id).name %></td>
      <td><%= deposit.term %></td>
      <td><%= deposit.rate %></td>
      <td><%= deposit.widthdrawal %></td>
      <td><%= deposit.refill %></td>
      <% if is_manager? %>
        <td>
          <%= link_to "Delete", deposit_path(deposit), class:"button red", method: :delete, data: { confirm: 'Are you sure?' }, style: 'font-size: 13px !important;' %>
          <%= link_to "Edit", edit_deposit_path(deposit), class:"button orange", style: 'font-size: 13px !important;' %>
        </td>
      <% end %>
    </tr>
    <% end %>
</table>
<% if is_manager? %>
  <button class="button green" style="float: left" onclick="location.href='<%=new_deposit_path%>'">New deposit</button>
<% end %>
</div>
</div>

app/views/deposits/new.html.erb
<title>Add Deposit</title>
<div class="middle">
<h1 class="h1-basic">New deposit</h1>
<%= render 'form' %>
<button class="button orange" style="float: left" onclick="location.href='/deposits'">Back</button>